name: live ci/cd-workflow
"on":
  push:
    branches:
      - live

## better to define all parameters as secrets under Environment secrets
jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      env_name: 'live'
      base_branch: 'live'
      AWS_ACCOUNT: "${{ secrets.AWS_ACCOUNT_NUMBER }}"
      STAGE: live
      REGION: us-east-1
      PROVCON: 1
      USER_POOL_ID: us-east-1_maiJOaOwE
      DASHBOARD_USER_POOL_ID: us-east-1_xr9tlK3N4
      db_env: aurora
      db_name: livecelitechcoredb
      aws_secret_store_arn: "${{ secrets.LIVE_AWS_SECRET_STORE_ARN }}"
      db_cluster_arn: "${{ secrets.LIVE_DB_CLUSTER_ARN }}"
      secret_stripe_key: "${{ secrets.LIVE_SECRET_STRIPE_KEY }}"
      MNO_URL: "${{ secrets.TEST_MNO_URL }}"
      DISTRIBUTOR_ID: "${{ secrets.TEST_DISTRIBUTOR_ID }}"
      INVENTORY_ID: "${{ secrets.TEST_INVENTORY_ID }}"
      API_KEY: "${{ secrets.TEST_API_KEY }}"
      AUTH: "${{ secrets.TEST_AUTH }}"
      ICCID_QUEUE_URL: live-iccid-queue.fifo
      auto_refill_bucket_name: live-core-qr-bucket
      minimum_batch_esim_count: 100
      XRAY_WRAPPER_FLAG: true
      DEVICE_INFO_API_KEY_SECRET_NAME: "${{ secrets.DEVICE_INFO_API_KEY_SECRET_NAME }}"
      BEE_API_ID: cohcx2j7eg
      DASHBOARD_API_ID: 18awng8l29
      USERPOOL_API_ID: ggxo6igr29
      CONSUMPTIONS_BUCKET: core-live-consumptions-reports
      RSP_URL: "${{secrets.TEST_RSP_URL}}"
      RSP_FRI: "${{secrets.TEST_RSP_FRI}}"
      RSP_SECRET: "${{secrets.TEST_RSP_SECRET}}"
      SENDGRID_KEY: "${{ secrets.SENDGRID_KEY }}"
      UNWIRED_LABS_SECRET_NAME: prod_unwiredlabs_api
      UNWIRED_LABS_BASE_URL: "https://us1.unwiredlabs.com/v2/process.php"
      SVIX_API_KEY: sk_lUDW_9YEy1nPz9xP4bxpPyRVwUYvZD35
      PRICE_LIST_BUCKET_NAME: price-list-live
      PRICE_LIST_KEY: all-price-list-items.csv
      IMSI_BUCKET_NAME: core-live-imsi-bucket
      STOCK_FOLDER_NAME: stock
      ONLINE_FOLDER_NAME: online
      LOADED_FOLDER_NAME: loaded
      IMSI_BUCKET: core-live-imsi-bucket
      MONITORING_ENABLED: true
      QR_CODE_LOGOS_BUCKET: core-live-qr-code-logos
      CDR_RECEIVING_BUCKET_NAME: telcomhub
      EXISTING_S3_BUCKET: true
      LOCATION_BUCKET_REGION: us-east-2
      CONSUMPTION_CHECK_ENABLED: true
      CONNECTIVITY_SCHEDULER_ENABLED: true
