name: qa ci/cd-workflow
"on":
  push:
    branches:
      - qa

## better to define all parameters as secrets under Environment secrets
jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      env_name: 'qa'
      base_branch: 'qa'
      AWS_ACCOUNT: "${{ secrets.AWS_ACCOUNT_NUMBER }}"
      STAGE: qa
      REGION: us-east-1
      PROVCON: 0
      USER_POOL_ID: us-east-1_ecVHm0GKT
      DASHBOARD_USER_POOL_ID: us-east-1_4jebWPUDW
      db_env: aurora
      db_name: qacelitechcoredb
      aws_secret_store_arn: "${{ secrets.TEST_AWS_SECRET_STORE_ARN }}"
      db_cluster_arn: "${{ secrets.TEST_DB_CLUSTER_ARN }}"
      secret_stripe_key: "${{ secrets.TEST_SECRET_STRIPE_KEY }}"
      MNO_URL: "${{ secrets.TEST_MNO_URL }}"
      DISTRIBUTOR_ID: "${{ secrets.TEST_DISTRIBUTOR_ID }}"
      INVENTORY_ID: "${{ secrets.TEST_INVENTORY_ID }}"
      API_KEY: "${{ secrets.TEST_API_KEY }}"
      AUTH: "${{ secrets.TEST_AUTH }}"
      ICCID_QUEUE_URL: qa-iccid-queue.fifo
      auto_refill_bucket_name: test-core-qr-bucket
      minimum_batch_esim_count: 10
      XRAY_WRAPPER_FLAG: true
      DEVICE_INFO_API_KEY_SECRET_NAME: "${{ secrets.DEVICE_INFO_API_KEY_SECRET_NAME }}"
      BEE_API_ID: 1bki1q3be6
      DASHBOARD_API_ID: pqua916yy1
      USERPOOL_API_ID: 41vnzvuo26
      CONSUMPTIONS_BUCKET: core-qa-consumptions-reports
      RSP_URL: "${{secrets.TEST_RSP_URL}}"
      RSP_FRI: "${{secrets.TEST_RSP_FRI}}"
      RSP_SECRET: "${{secrets.TEST_RSP_SECRET}}"
      SENDGRID_KEY: "${{ secrets.SENDGRID_KEY }}"
      UNWIRED_LABS_SECRET_NAME: staging_unwiredlabs_api
      UNWIRED_LABS_BASE_URL: "https://us1.unwiredlabs.com/v2/process.php"
      SVIX_API_KEY: testsk_kZbbmXTudaMnYrEfc2W-h4WSz0-AF6Bk
      PRICE_LIST_BUCKET_NAME: price-list-qa
      PRICE_LIST_KEY: all-price-list-items.csv
      IMSI_BUCKET_NAME: core-qa-imsi-bucket
      STOCK_FOLDER_NAME: stock
      ONLINE_FOLDER_NAME: online
      LOADED_FOLDER_NAME: loaded
      IMSI_BUCKET: core-qa-imsi-bucket
      MONITORING_ENABLED: false
      QR_CODE_LOGOS_BUCKET: core-qa-qr-code-logos
      CDR_RECEIVING_BUCKET_NAME: core-qa-emulate-cdr-bucket
      EXISTING_S3_BUCKET: true
      LOCATION_BUCKET_REGION: us-east-1
      CONSUMPTION_CHECK_ENABLED: false
      CONNECTIVITY_SCHEDULER_ENABLED: false
