name: feature ci/cd-workflow
on:
  push:
    branches:
      - feature/*

## better to define all parameters as secrets under Environment secrets
jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      env_name: 'feature'
      base_branch: 'master'
      drop_create_db: true ## !!!! IMPORTANT DO NOT SET THIS VALUE TO TRUE IN CASE OF PROD
      AWS_ACCOUNT: "${{ secrets.AWS_ACCOUNT_NUMBER }}"
      STAGE: test
      REGION: us-east-1
      PROVCON: 0
      USER_POOL_ID: us-east-1_AWebLRzDl
      DASHBOARD_USER_POOL_ID: us-east-1_HQQmgFi3I
      db_env: aurora
      db_name: testcelitechcoredb
      aws_secret_store_arn: "${{ secrets.TEST_AWS_SECRET_STORE_ARN }}"
      db_cluster_arn: "${{ secrets.TEST_DB_CLUSTER_ARN }}"
      secret_stripe_key: "${{ secrets.TEST_SECRET_STRIPE_KEY }}"
      MNO_URL: "${{secrets.TEST_MNO_URL}}"
      DISTRIBUTOR_ID: "${{secrets.TEST_DISTRIBUTOR_ID}}"
      INVENTORY_ID: "${{secrets.TEST_INVENTORY_ID}}"
      API_KEY: "${{secrets.TEST_API_KEY}}"
      AUTH: "${{secrets.TEST_AUTH}}"
      ICCID_QUEUE_URL: test-iccid-queue.fifo
      auto_refill_bucket_name: test-core-qr-bucket
      minimum_batch_esim_count: 10
      XRAY_WRAPPER_FLAG: false
      DEVICE_INFO_API_KEY_SECRET_NAME: "${{ secrets.DEVICE_INFO_API_KEY_SECRET_NAME }}"
      BEE_API_ID: tshnuiufz7
      DASHBOARD_API_ID: 3i9p1rvnh4
      USERPOOL_API_ID: wv1yjr74zh
      CONSUMPTIONS_BUCKET: core-test-consumptions-reports
      RSP_URL: "${{secrets.TEST_RSP_URL}}"
      RSP_FRI: "${{secrets.TEST_RSP_FRI}}"
      RSP_SECRET: "${{secrets.TEST_RSP_SECRET}}"
      SENDGRID_KEY: "${{ secrets.SENDGRID_KEY }}"
      UNWIRED_LABS_SECRET_NAME: staging_unwiredlabs_api
      UNWIRED_LABS_BASE_URL: "https://us1.unwiredlabs.com/v2/process.php"
      SVIX_API_KEY: testsk_mmOeW-YmIFeo-SYTE-1CV3hpFH8nXwbl
      PRICE_LIST_BUCKET_NAME: price-list-test
      PRICE_LIST_KEY: all-price-list-items.csv
      IMSI_BUCKET_NAME: core-test-imsi-bucket
      STOCK_FOLDER_NAME: stock
      ONLINE_FOLDER_NAME: online
      LOADED_FOLDER_NAME: loaded
      IMSI_BUCKET: core-test-imsi-bucket
      MONITORING_ENABLED: false
      QR_CODE_LOGOS_BUCKET: core-test-qr-code-logos
      CDR_RECEIVING_BUCKET_NAME: core-test-emulate-cdr-bucket
      EXISTING_S3_BUCKET: true
      LOCATION_BUCKET_REGION: us-east-1
      CONSUMPTION_CHECK_ENABLED: false
      CONNECTIVITY_SCHEDULER_ENABLED: false
